/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Entity.Users;
import Utilities.Tools;

/**
 *
 * @author Ahmed
 */
public class Accounts_form extends javax.swing.JFrame {

    /**
     * Creates new form Accounts_form
     */
    public Accounts_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        customButton6 = new CustomGUI.CustomButton();
        username = new CustomGUI.CustomTextBox();
        customButton7 = new CustomGUI.CustomButton();
        jLabel3 = new javax.swing.JLabel();
        ban = new CustomGUI.CustomButton();
        password = new CustomGUI.CustomTextBox();
        customButton2 = new CustomGUI.CustomButton();
        customButton3 = new CustomGUI.CustomButton();
        customButton4 = new CustomGUI.CustomButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTable = new javax.swing.JTable();
        recacc = new CustomGUI.CustomButton();
        Search = new CustomGUI.CustomTextBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username :");

        customButton6.setText("Search");
        customButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customButton6.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton6.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton6.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton6ActionPerformed(evt);
            }
        });

        customButton7.setText("Back");
        customButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customButton7.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton7.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton7.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton7ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password :");

        ban.setText("Ban");
        ban.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ban.setMaximumSize(new java.awt.Dimension(83, 25));
        ban.setMinimumSize(new java.awt.Dimension(83, 25));
        ban.setPreferredSize(new java.awt.Dimension(83, 25));
        ban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banActionPerformed(evt);
            }
        });

        customButton2.setText("Delete");
        customButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customButton2.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton2.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton2.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton2ActionPerformed(evt);
            }
        });

        customButton3.setText("Clear");
        customButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customButton3.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton3.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton3.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton3ActionPerformed(evt);
            }
        });

        customButton4.setText("Get All");
        customButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customButton4.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton4.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton4.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });

        DataTable.setAutoCreateRowSorter(true);
        DataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password", "Is banned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataTable.setAutoscrolls(false);
        DataTable.setGridColor(new java.awt.Color(102, 102, 102));
        DataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DataTable);

        recacc.setText("Recover Last Deleted");
        recacc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        recacc.setMaximumSize(new java.awt.Dimension(83, 25));
        recacc.setMinimumSize(new java.awt.Dimension(83, 25));
        recacc.setPreferredSize(new java.awt.Dimension(83, 25));
        recacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recaccActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ban, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(customButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(customButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(recacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 30, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ban, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recacc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Users u = new Users();
    Users rec = new Users();

    private void setvalues(String Username, String Password, String banned) {
        u.setUsername(Username);
        u.setPassword(Password);
        u.setBanned(banned);
    }

    private void setrec(Users user) {
        rec = user;
    }

    private void cleardata() {
        Tools.clearTextFields(this);
    }
    private void customButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton7ActionPerformed
        this.dispose();
        Tools.openForm(new main());
    }//GEN-LAST:event_customButton7ActionPerformed

    private void banActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banActionPerformed
        if (u.getUsername().equals("admin")) {
            Tools.showMessageDialog("admin cannot be banned");
            return;
        }
        if (u.isBanned()) {
            if (Tools.showConfirmationDialog("Are you sure you want to unban this account " + username.getText())) {
                u.setBanned("No");
                u.update();
                u.getAllRows(DataTable);
                cleardata();
            }
        } else {
            if (Tools.showConfirmationDialog("Are you sure you want to ban this account " + username.getText())) {
                u.setBanned("Yes");
                u.update();
                u.getAllRows(DataTable);
                cleardata();
            }

        }
        ban.setText("Ban");
    }//GEN-LAST:event_banActionPerformed

    private void customButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton2ActionPerformed
        if (u.getUsername().equals("admin")) {
            Tools.showMessageDialog("admin cannot be deleted");
            return;
        }
        if (Tools.showConfirmationDialog("Are you sure you want to delete this account " + username.getText())) {
            setrec(u);
            u.delete();
            u.getAllRows(DataTable);
            cleardata();
            recacc.setEnabled(true);
        }
    }//GEN-LAST:event_customButton2ActionPerformed

    private void DataTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataTableMouseClicked
        try {
            int row = DataTable.getSelectedRow();
            String Username = DataTable.getValueAt(row, 0).toString();
            String pass = DataTable.getValueAt(row, 1).toString();
            String banned = DataTable.getValueAt(row, 2).toString();

            username.setText(Username);
            username.setText(pass);

            setvalues(Username, pass, banned);
            if ("Yes".equals(banned)) {
                ban.setText("UnBan");
            } else if ("No".equals(banned)) {
                ban.setText("Ban");
            }

        } catch (Exception ex) {
            Tools.showMessageDialog(ex.getMessage());
        }
    }//GEN-LAST:event_DataTableMouseClicked

    private void customButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton3ActionPerformed
        cleardata();
    }//GEN-LAST:event_customButton3ActionPerformed

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        u.getAllRows(DataTable);
    }//GEN-LAST:event_customButton4ActionPerformed

    private void recaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recaccActionPerformed
        if (Tools.showConfirmationDialog("do you want to recover account (" + rec.getUsername() + " )")) {
            rec.add();
            u.getAllRows(DataTable);
            recacc.setEnabled(false);
        }
    }//GEN-LAST:event_recaccActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cleardata();
        u.getAllRows(DataTable);
        DataTable.setBorder(null);
        DataTable.getTableHeader().setReorderingAllowed(false);
        recacc.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void customButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton6ActionPerformed
        String search = "select * from Users where Username like '%" + Search.getText() + "%'";
        u.filter(search, DataTable);
    }//GEN-LAST:event_customButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accounts_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accounts_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accounts_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accounts_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accounts_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataTable;
    private CustomGUI.CustomTextBox Search;
    private CustomGUI.CustomButton ban;
    private CustomGUI.CustomButton customButton2;
    private CustomGUI.CustomButton customButton3;
    private CustomGUI.CustomButton customButton4;
    private CustomGUI.CustomButton customButton6;
    private CustomGUI.CustomButton customButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private CustomGUI.CustomTextBox password;
    private CustomGUI.CustomButton recacc;
    private CustomGUI.CustomTextBox username;
    // End of variables declaration//GEN-END:variables
}
