/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Utilities.Tools;

/**
 *
 * @author Ahmed
 */
public class Department_form extends javax.swing.JFrame {

    /**
     * Creates new form Department_form
     */
    public Department_form() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dpnumber = new CustomGUI.CustomTextBox();
        dpname = new CustomGUI.CustomTextBox();
        dplocation = new CustomGUI.CustomTextBox();
        addb = new CustomGUI.CustomButton();
        updateb = new CustomGUI.CustomButton();
        delb = new CustomGUI.CustomButton();
        customButton4 = new CustomGUI.CustomButton();
        customButton5 = new CustomGUI.CustomButton();
        customButton6 = new CustomGUI.CustomButton();
        customButton7 = new CustomGUI.CustomButton();
        rad1 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Searchbar = new CustomGUI.CustomTextBox();
        customButton9 = new CustomGUI.CustomButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DateTable = new javax.swing.JTable();
        recDep = new CustomGUI.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Department Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Department Number :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Department Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Location :");

        dpnumber.setEditable(false);
        dpnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpnumberActionPerformed(evt);
            }
        });

        dpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpnameActionPerformed(evt);
            }
        });

        addb.setText("Add");
        addb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addb.setMaximumSize(new java.awt.Dimension(83, 25));
        addb.setMinimumSize(new java.awt.Dimension(83, 25));
        addb.setPreferredSize(new java.awt.Dimension(83, 25));
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        updateb.setText("Ubdate");
        updateb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        delb.setText("Delete");
        delb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbActionPerformed(evt);
            }
        });

        customButton4.setText("Find");
        customButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });

        customButton5.setText("Get All");
        customButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });

        customButton6.setText("Clear");
        customButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton6ActionPerformed(evt);
            }
        });

        customButton7.setText("Back");
        customButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton7.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton7.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton7.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton7ActionPerformed(evt);
            }
        });

        rad1.setBackground(new java.awt.Color(255, 255, 255));
        rad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad1.setText("Name");

        rad2.setBackground(new java.awt.Color(255, 255, 255));
        rad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad2.setSelected(true);
        rad2.setText("Number");

        rad3.setBackground(new java.awt.Color(255, 255, 255));
        rad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad3.setText("Location");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("search by :");

        customButton9.setText("Search");
        customButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton9.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton9.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton9.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton9ActionPerformed(evt);
            }
        });

        DateTable.setAutoCreateRowSorter(true);
        DateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DateTable.setAutoscrolls(false);
        DateTable.setGridColor(new java.awt.Color(102, 102, 102));
        DateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DateTable);

        recDep.setText("Recover Last Deleted");
        recDep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(rad2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rad1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(144, 144, 144))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dpname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dpnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                .addComponent(dplocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(recDep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(dpnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dpname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dplocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recDep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rad1)
                            .addComponent(rad3)
                            .addComponent(rad2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Department d = new Department();
    //LinkedList<Department> rec = new LinkedList<>();
    Department rec = new Department();

    private void setvalues() {
        d.setDepartmentName(dpname.getText());
        d.setDepartmentNumber(Integer.parseInt(dpnumber.getText()));
        d.setLocation(dplocation.getText());
    }

    private void setrec(int num, String name, String loc) {
        rec.setDepartmentName(name);
        rec.setDepartmentNumber(num);
        rec.setLocation(loc);
    }

    private void cleardata() {
        Tools.clearTextFields(this);
        dpnumber.setText(d.getAutoNumber());
        addb.setEnabled(true);
        updateb.setEnabled(false);
        delb.setEnabled(false);
        dpname.requestFocus();
    }

    private void delbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbActionPerformed
        if (Tools.showConfirmationDialog("Are you sure you want to delete this Department " + dpnumber.getText())) {
            setvalues();
            setrec(d.getDepartmentNumber(), d.getDepartmentName(), d.getLocation());
            d.delete();
            d.getAllRows(DateTable);
            cleardata();
            recDep.setEnabled(true);
        }
    }//GEN-LAST:event_delbActionPerformed

    private void customButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton7ActionPerformed
        this.dispose();
        Tools.openForm(new main());
    }//GEN-LAST:event_customButton7ActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        setvalues();
        d.add();
        d.getAllRows(DateTable);
        cleardata();
    }//GEN-LAST:event_addbActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        searchgroup.add(rad1);
        searchgroup.add(rad2);
        searchgroup.add(rad3);
        cleardata();
        d.getAllRows(DateTable);
        DateTable.setBorder(null);
        DateTable.getTableHeader().setReorderingAllowed(false);
        recDep.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void customButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton6ActionPerformed
        cleardata();
    }//GEN-LAST:event_customButton6ActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        setvalues();
        d.update();
        d.getAllRows(DateTable);
        cleardata();
    }//GEN-LAST:event_updatebActionPerformed

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
        d.getAllRows(DateTable);
    }//GEN-LAST:event_customButton5ActionPerformed

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        String dnum = (String) Tools.showInputDialog("Enter Department Number");
        if (dnum != null) {
            d.setDepartmentNumber(Integer.parseInt(dnum));
            d.getOneRow(DateTable);
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void DateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTableMouseClicked
        try {
            int row = DateTable.getSelectedRow();
            String Dpnum = DateTable.getValueAt(row, 0).toString();
            String Dpnam = DateTable.getValueAt(row, 1).toString();
            String Dpdep = DateTable.getValueAt(row, 2).toString();

            dpnumber.setText(Dpnum);
            dpname.setText(Dpnam);
            dplocation.setText(Dpdep);

            addb.setEnabled(false);
            updateb.setEnabled(true);
            delb.setEnabled(true);
        } catch (Exception ex) {
            Tools.showMessageDialog(ex.getMessage());
        }
    }//GEN-LAST:event_DateTableMouseClicked

    private void recDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recDepActionPerformed
        if (Tools.showConfirmationDialog("do you want to recover Department (" + rec.getDepartmentName()+ " , " + rec.getLocation() + " )")) {

            int row = DateTable.getRowCount();
            for (int i = 0; i < row; i++) {
                int val = Integer.parseInt(DateTable.getValueAt(i, 0).toString());
                if (rec.getDepartmentNumber() == val) {
                    rec.setDepartmentNumber(Integer.parseInt(rec.getAutoNumber()));
                }
            }

            rec.add();
            d.getAllRows(DateTable);
            recDep.setEnabled(false);
        }
    }//GEN-LAST:event_recDepActionPerformed

    private void customButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton9ActionPerformed
        String search = "select * from DepartmentData where ";
        if (rad2.isSelected()) {
            search += "DepartmentNumber ";
        } else if (rad1.isSelected()) {
            search += "Department ";
        } else {
            search += "Location ";
        }
        search += " like '%" + Searchbar.getText() + "%'";
        d.filter(search, DateTable);
    }//GEN-LAST:event_customButton9ActionPerformed

    private void dpnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpnumberActionPerformed

    private void dpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DateTable;
    private CustomGUI.CustomTextBox Searchbar;
    private CustomGUI.CustomButton addb;
    private CustomGUI.CustomButton customButton4;
    private CustomGUI.CustomButton customButton5;
    private CustomGUI.CustomButton customButton6;
    private CustomGUI.CustomButton customButton7;
    private CustomGUI.CustomButton customButton9;
    private CustomGUI.CustomButton delb;
    private CustomGUI.CustomTextBox dplocation;
    private CustomGUI.CustomTextBox dpname;
    private CustomGUI.CustomTextBox dpnumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private CustomGUI.CustomButton recDep;
    private javax.swing.ButtonGroup searchgroup;
    private CustomGUI.CustomButton updateb;
    // End of variables declaration//GEN-END:variables
}
