/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Entity.Department;
import Entity.Employee;
import Entity.EmployeePhones;
import Utilities.Tools;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author Ahmed
 */
public class Employee_report extends javax.swing.JFrame {

    /**
     * Creates new form Department_report
     */
    public Employee_report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Searchgroup = new javax.swing.ButtonGroup();
        customButton1 = new CustomGUI.CustomButton();
        jLabel1 = new javax.swing.JLabel();
        customButton3 = new CustomGUI.CustomButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DateTable = new javax.swing.JTable();
        rad2 = new javax.swing.JRadioButton();
        rad1 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Searchbar = new CustomGUI.CustomTextBox();
        customButton9 = new CustomGUI.CustomButton();
        rad4 = new javax.swing.JRadioButton();
        rad5 = new javax.swing.JRadioButton();
        rad6 = new javax.swing.JRadioButton();
        rad7 = new javax.swing.JRadioButton();
        rad8 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        customButton1.setText("Print report");
        customButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employee Report");

        customButton3.setText("Back");
        customButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        customButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton3ActionPerformed(evt);
            }
        });

        DateTable.setAutoCreateRowSorter(true);
        DateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "Salary", "Hiring Date", "Birth Date", "Department Number", "Department "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DateTable.getTableHeader().setResizingAllowed(false);
        DateTable.getTableHeader().setReorderingAllowed(false);
        DateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DateTable);

        rad2.setBackground(new java.awt.Color(255, 255, 255));
        rad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad2.setText("Name");
        rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2ActionPerformed(evt);
            }
        });

        rad1.setBackground(new java.awt.Color(255, 255, 255));
        rad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad1.setSelected(true);
        rad1.setText("Number");

        rad3.setBackground(new java.awt.Color(255, 255, 255));
        rad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad3.setText("Address");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Search by :");

        customButton9.setText("Search");
        customButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton9.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton9.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton9.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton9ActionPerformed(evt);
            }
        });

        rad4.setBackground(new java.awt.Color(255, 255, 255));
        rad4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad4.setText("Salary");

        rad5.setBackground(new java.awt.Color(255, 255, 255));
        rad5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad5.setText("Birth date");

        rad6.setBackground(new java.awt.Color(255, 255, 255));
        rad6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad6.setText("hiring date");

        rad7.setBackground(new java.awt.Color(255, 255, 255));
        rad7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad7.setText("Department");

        rad8.setBackground(new java.awt.Color(255, 255, 255));
        rad8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad8.setText("Deparment number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rad7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rad1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rad5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Searchbar, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(customButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(449, 449, 449)
                                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(457, 457, 457)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rad2)
                                .addComponent(rad1)
                                .addComponent(rad4)
                                .addComponent(rad5)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad6)
                            .addComponent(rad8)
                            .addComponent(rad7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Employee().getAllRows(DateTable);
        Tools.setTableHeaderAppearance(DateTable);
        Searchgroup.add(rad1);
        Searchgroup.add(rad2);
        Searchgroup.add(rad3);
        Searchgroup.add(rad4);
        Searchgroup.add(rad5);
        Searchgroup.add(rad6);
        Searchgroup.add(rad7);
        Searchgroup.add(rad8);        
        DateTable.getTableHeader().setReorderingAllowed(true);
    }//GEN-LAST:event_formWindowOpened

    private void customButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton3ActionPerformed
        this.dispose();
        Tools.openForm(new Reports_form());
    }//GEN-LAST:event_customButton3ActionPerformed

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        try {
            MessageFormat header = new MessageFormat("Employee Report");
            MessageFormat footer = new MessageFormat("Page - {0}");
            DateTable.print(JTable.PrintMode.FIT_WIDTH,header,footer);
        } catch (PrinterException ex) {
            Tools.showMessageDialog(ex.getMessage());
        }
    }//GEN-LAST:event_customButton1ActionPerformed

    private void DateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTableMouseClicked
        
    }//GEN-LAST:event_DateTableMouseClicked

    private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad2ActionPerformed

    private void customButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton9ActionPerformed
        String search = "select * from EmployeeData where ";
        if (rad1.isSelected()) {
            search += "Number ";
        } else if (rad2.isSelected()) {
            search += "Name ";
        } else if (rad3.isSelected()) {
            search += "Address ";
        } else if (rad4.isSelected()) {
            search += "Salary ";
        } else if (rad5.isSelected()) {
            search += "BirthDate ";
        } else if (rad6.isSelected()) {
            search += "HiringDate ";
        } else if (rad7.isSelected()) {
            search += "Department ";
        } else if (rad8.isSelected()){
            search += "DepartmentNumber ";
        }else{
            String s = new EmployeePhones().getEmployeeNumberByPhone(Searchbar.getText());
            search += "NUMBER like '%" + s + "%'";
        }
        if(rad1.isSelected()||rad2.isSelected()||rad3.isSelected()||rad4.isSelected()||rad5.isSelected()||rad6.isSelected()||rad7.isSelected()||rad8.isSelected()){
            search += " like '%" + Searchbar.getText() + "%'";
        }
        new Employee().filter(search, DateTable);
    }//GEN-LAST:event_customButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DateTable;
    private CustomGUI.CustomTextBox Searchbar;
    private javax.swing.ButtonGroup Searchgroup;
    private CustomGUI.CustomButton customButton1;
    private CustomGUI.CustomButton customButton3;
    private CustomGUI.CustomButton customButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JRadioButton rad5;
    private javax.swing.JRadioButton rad6;
    private javax.swing.JRadioButton rad7;
    private javax.swing.JRadioButton rad8;
    // End of variables declaration//GEN-END:variables
}
