/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Database.MysqlDatabaseManager;
import Entity.Department;
import Entity.Employee;
import Entity.EmployeePhones;
import Utilities.Tools;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed
 */
public class Employee_form extends javax.swing.JFrame {

    /**
     * Creates new form Employee_form
     */
    public Employee_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        Searchgroup = new javax.swing.ButtonGroup();
        head = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Empnam = new CustomGUI.CustomTextBox();
        Empnum = new CustomGUI.CustomTextBox();
        Empsal = new CustomGUI.CustomTextBox();
        Empadd = new CustomGUI.CustomTextBox();
        Dep = new CustomGUI.CustomComboBox();
        Emphi = new com.toedter.calendar.JDateChooser();
        Empbi = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        DateTable = new javax.swing.JTable();
        customButton4 = new CustomGUI.CustomButton();
        customButton5 = new CustomGUI.CustomButton();
        customButton6 = new CustomGUI.CustomButton();
        addb = new CustomGUI.CustomButton();
        updateb = new CustomGUI.CustomButton();
        delb = new CustomGUI.CustomButton();
        customButton7 = new CustomGUI.CustomButton();
        rad2 = new javax.swing.JRadioButton();
        rad1 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        Searchbar = new CustomGUI.CustomTextBox();
        customButton9 = new CustomGUI.CustomButton();
        rad4 = new javax.swing.JRadioButton();
        rad5 = new javax.swing.JRadioButton();
        rad6 = new javax.swing.JRadioButton();
        rad7 = new javax.swing.JRadioButton();
        rad8 = new javax.swing.JRadioButton();
        customButton10 = new CustomGUI.CustomButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        phones = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        Emppho = new CustomGUI.CustomTextBox();
        addp = new CustomGUI.CustomButton();
        delp2 = new CustomGUI.CustomButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        head.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        head.setText("Employee Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Number :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Address :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Salary :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Birth Date :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("HireDate :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Department :");

        Empnum.setEditable(false);

        Dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepActionPerformed(evt);
            }
        });

        DateTable.setAutoCreateRowSorter(true);
        DateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Address", "Salary", "Hiring Date", "Birth Date", "Department Number", "Department "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DateTable.getTableHeader().setResizingAllowed(false);
        DateTable.getTableHeader().setReorderingAllowed(false);
        DateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(DateTable);

        customButton4.setText("Find");
        customButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });

        customButton5.setText("Get All");
        customButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });

        customButton6.setText("Clear");
        customButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton6ActionPerformed(evt);
            }
        });

        addb.setText("Add");
        addb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addb.setMaximumSize(new java.awt.Dimension(83, 25));
        addb.setMinimumSize(new java.awt.Dimension(83, 25));
        addb.setPreferredSize(new java.awt.Dimension(83, 25));
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        updateb.setText("Ubdate");
        updateb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebActionPerformed(evt);
            }
        });

        delb.setText("Delete");
        delb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbActionPerformed(evt);
            }
        });

        customButton7.setText("Back");
        customButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton7.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton7.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton7.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton7ActionPerformed(evt);
            }
        });

        rad2.setBackground(new java.awt.Color(255, 255, 255));
        rad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad2.setText("Name");
        rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2ActionPerformed(evt);
            }
        });

        rad1.setBackground(new java.awt.Color(255, 255, 255));
        rad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad1.setSelected(true);
        rad1.setText("Number");

        rad3.setBackground(new java.awt.Color(255, 255, 255));
        rad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad3.setText("Address");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Search by :");

        customButton9.setText("Search");
        customButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton9.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton9.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton9.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton9ActionPerformed(evt);
            }
        });

        rad4.setBackground(new java.awt.Color(255, 255, 255));
        rad4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad4.setText("Salary");

        rad5.setBackground(new java.awt.Color(255, 255, 255));
        rad5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad5.setText("Birth date");

        rad6.setBackground(new java.awt.Color(255, 255, 255));
        rad6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad6.setText("hiring date");

        rad7.setBackground(new java.awt.Color(255, 255, 255));
        rad7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad7.setText("Department");

        rad8.setBackground(new java.awt.Color(255, 255, 255));
        rad8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad8.setText("Deparment number");

        customButton10.setText("+");
        customButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton10.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton10.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton10.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton10ActionPerformed(evt);
            }
        });

        phones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        phones.setGridColor(new java.awt.Color(102, 102, 102));
        phones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phonesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(phones);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Phone :");

        addp.setText("+");
        addp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addp.setMaximumSize(new java.awt.Dimension(83, 25));
        addp.setMinimumSize(new java.awt.Dimension(83, 25));
        addp.setPreferredSize(new java.awt.Dimension(83, 25));
        addp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpActionPerformed(evt);
            }
        });

        delp2.setText("Delete All Phones");
        delp2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rad7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(rad5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rad6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(rad1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rad8, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(rad4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(delp2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                    .addComponent(Empnam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Empadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Empsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Dep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Empnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Emphi, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                                    .addComponent(Empbi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Emppho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(customButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Searchbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(head)
                .addGap(686, 686, 686))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Empnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Empnam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Empadd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Empsal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(Emphi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(Empbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(customButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Dep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(Emppho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(updateb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(delp2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(rad2)
                                .addComponent(rad1)
                                .addComponent(rad4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad5)
                            .addComponent(rad6)
                            .addComponent(rad8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rad7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Employee e = new Employee();
    Department dep = new Department();
    SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
    EmployeePhones p = new EmployeePhones();

    private void setvalues(Employee emp) {
        emp.setEmployeeNumber(Integer.parseInt(Empnum.getText()));
        emp.setEmployeeName(Empnam.getText());
        emp.setEmployeeAddress(Empadd.getText());
        emp.setSalary(Double.parseDouble(Empsal.getText()));
        String HDate = f.format(Emphi.getDate());
        String BDate = f.format(Empbi.getDate());
        emp.setHireDate(HDate);
        emp.setBirthDate(BDate);
        String dn = dep.getValue(Dep.getSelectedItem().toString());
        emp.setDepartmentNumber(Integer.parseInt(dn));
        p.setEmployeeNumber(Integer.parseInt(Empnum.getText()));
    }

    private void cleardata() {
        Tools.clearTextFields(this);
        Empnum.setText(e.getAutoNumber());
        addb.setEnabled(true);
        updateb.setEnabled(false);
        delb.setEnabled(false);
        delp2.setEnabled(false);
        delp2ActionPerformed(null);
        Empnam.requestFocus();
    }

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        String dnum = (String) Tools.showInputDialog("Enter Employee Number");
        if (dnum != null) {
            e.setEmployeeNumber(Integer.parseInt(dnum));
            e.getOneRow(DateTable);
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
        e.getAllRows(DateTable);
    }//GEN-LAST:event_customButton5ActionPerformed

    private void customButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton6ActionPerformed
        cleardata();
    }//GEN-LAST:event_customButton6ActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        setvalues(e);
        e.add();
        for (int i = 0; i < phones.getRowCount(); i++) {
            p.setPhone(phones.getValueAt(i, 0).toString());
            p.add();
        }
        e.getAllRows(DateTable);
        cleardata();
    }//GEN-LAST:event_addbActionPerformed

    private void updatebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebActionPerformed
        setvalues(e);
        e.update();
        p.deleteAllPhones();
        for (int i = 0; i < phones.getRowCount(); i++) {
            p.setPhone(phones.getValueAt(i, 0).toString());
            p.add();
        }
        e.getAllRows(DateTable);
        cleardata();
    }//GEN-LAST:event_updatebActionPerformed

    private void delbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbActionPerformed
        if (Tools.showConfirmationDialog("Are you sure you want to delete this Employee ( " + Empnum.getText() + " , " + Empnam.getText() + " )")) {
            setvalues(e);
            ///setvalues(rece);

            p.setEmployeeNumber(Integer.parseInt(Empnum.getText()));
            p.deleteAllPhones();
            e.delete();
            e.getAllRows(DateTable);
            cleardata();
            //recEmp.setEnabled(true);
        }
    }//GEN-LAST:event_delbActionPerformed

    private void customButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton7ActionPerformed
        this.dispose();
        Tools.openForm(new main());
    }//GEN-LAST:event_customButton7ActionPerformed

    private void customButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton9ActionPerformed
        String search = "select * from EmployeeData where ";
        if (rad1.isSelected()) {
            search += "Number ";
        } else if (rad2.isSelected()) {
            search += "Name ";
        } else if (rad3.isSelected()) {
            search += "Address ";
        } else if (rad4.isSelected()) {
            search += "Salary ";
        } else if (rad5.isSelected()) {
            search += "BirthDate ";
        } else if (rad6.isSelected()) {
            search += "HiringDate ";
        } else if (rad7.isSelected()) {
            search += "Department ";
        } else if (rad8.isSelected()) {
            search += "DepartmentNumber ";
        } else {
            String s = p.getEmployeeNumberByPhone(Searchbar.getText());
            search += "Number like '%" + s + "%'";
        }
        if (rad1.isSelected() || rad2.isSelected() || rad3.isSelected() || rad4.isSelected() || rad5.isSelected() || rad6.isSelected() || rad7.isSelected() || rad8.isSelected()) {
            search += " like '%" + Searchbar.getText() + "%'";
        }
        e.filter(search, DateTable);
    }//GEN-LAST:event_customButton9ActionPerformed

    private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Searchgroup.add(rad1);
        Searchgroup.add(rad2);
        Searchgroup.add(rad3);
        Searchgroup.add(rad4);
        Searchgroup.add(rad5);
        Searchgroup.add(rad6);
        Searchgroup.add(rad7);
        Searchgroup.add(rad8);
        cleardata();
        e.getAllRows(DateTable);
        DateTable.getTableHeader().setReorderingAllowed(false);
        MysqlDatabaseManager.fillComboBox("DepartmentData", "Department", Dep);
        phones.getTableHeader().setReorderingAllowed(false);

        //recEmp.setVisible(false);
        //addp.setEnabled(true);
        //delp.setVisible(false);
        //recpho.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void customButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton10ActionPerformed
        int num = Integer.parseInt(dep.getAutoNumber());
        String nam = (String) Tools.showInputDialog("Enter Department Name");
        if (nam != null) {
            String loc = (String) Tools.showInputDialog("Enter Department Location");
            if (loc != null) {
                dep.setDepartmentName(nam);
                dep.setDepartmentNumber(num);
                dep.setLocation(loc);
                dep.add();
            } else {
                Tools.showMessageDialog("the adding is canceled");
            }
        } else {
            Tools.showMessageDialog("the adding is canceled");
        }
        MysqlDatabaseManager.fillComboBox("Department", "Department", Dep);
    }//GEN-LAST:event_customButton10ActionPerformed

    private void DateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTableMouseClicked
        try {
            int row = DateTable.getSelectedRow();
            String Depn = DateTable.getValueAt(row, 6).toString();
            Empnum.setText(DateTable.getValueAt(row, 0).toString());
            Empnam.setText(DateTable.getValueAt(row, 1).toString());
            Empadd.setText(DateTable.getValueAt(row, 2).toString());
            Empsal.setText(DateTable.getValueAt(row, 3).toString());
            Date hd = f.parse(DateTable.getValueAt(row, 4).toString());
            Date bd = f.parse(DateTable.getValueAt(row, 5).toString());
            Emphi.setDate(hd);
            Empbi.setDate(bd);
            Dep.setSelectedItem(DateTable.getValueAt(row, 7).toString());
            p.setEmployeeNumber(Integer.parseInt(Empnum.getText()));
            p.getAllRows(phones);
            addb.setEnabled(false);
            updateb.setEnabled(true);
            delb.setEnabled(true);
            delp2.setEnabled(true);
        } catch (Exception ex) {
            Tools.showMessageDialog(ex.getMessage());
        }

    }//GEN-LAST:event_DateTableMouseClicked

    private void addpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpActionPerformed
        DefaultTableModel mod = (DefaultTableModel) phones.getModel();
        mod.addRow(new Object[]{Emppho.getText()});
        Emppho.setText("");
        Emppho.requestFocus();
    }//GEN-LAST:event_addpActionPerformed

    private void delp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delp2ActionPerformed
        DefaultTableModel mod = (DefaultTableModel) phones.getModel();
        mod.setNumRows(0);
    }//GEN-LAST:event_delp2ActionPerformed

    private void phonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phonesMouseClicked
        /*
        try {
            int row = DateTable.getSelectedRow();
            Emppho.setText(DateTable.getValueAt(row, 0).toString());
            addp.setEnabled(false);
            delp.setEnabled(true);
        } catch (Exception ex) {
            tools.tools.msgBox(ex.getMessage());
        }
         */
    }//GEN-LAST:event_phonesMouseClicked

    private void DepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DateTable;
    private CustomGUI.CustomComboBox Dep;
    private CustomGUI.CustomTextBox Empadd;
    private com.toedter.calendar.JDateChooser Empbi;
    private com.toedter.calendar.JDateChooser Emphi;
    private CustomGUI.CustomTextBox Empnam;
    private CustomGUI.CustomTextBox Empnum;
    private CustomGUI.CustomTextBox Emppho;
    private CustomGUI.CustomTextBox Empsal;
    private CustomGUI.CustomTextBox Searchbar;
    private javax.swing.ButtonGroup Searchgroup;
    private CustomGUI.CustomButton addb;
    private CustomGUI.CustomButton addp;
    private CustomGUI.CustomButton customButton10;
    private CustomGUI.CustomButton customButton4;
    private CustomGUI.CustomButton customButton5;
    private CustomGUI.CustomButton customButton6;
    private CustomGUI.CustomButton customButton7;
    private CustomGUI.CustomButton customButton9;
    private CustomGUI.CustomButton delb;
    private CustomGUI.CustomButton delp2;
    private javax.swing.JLabel head;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable phones;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JRadioButton rad5;
    private javax.swing.JRadioButton rad6;
    private javax.swing.JRadioButton rad7;
    private javax.swing.JRadioButton rad8;
    private CustomGUI.CustomButton updateb;
    // End of variables declaration//GEN-END:variables
}
