/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Database.MysqlDatabaseManager;
import Entity.Department;
import Entity.Project;
import Utilities.Tools;

/**
 *
 * @author Ahmed
 */
public class Project_form extends javax.swing.JFrame {

    /**
     * Creates new form Project_form
     */
    public Project_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchgroup = new javax.swing.ButtonGroup();
        rad1 = new javax.swing.JRadioButton();
        pname = new CustomGUI.CustomTextBox();
        rad3 = new javax.swing.JRadioButton();
        plocation = new CustomGUI.CustomTextBox();
        jLabel5 = new javax.swing.JLabel();
        addp = new CustomGUI.CustomButton();
        Searchbar = new CustomGUI.CustomTextBox();
        updatep = new CustomGUI.CustomButton();
        customButton9 = new CustomGUI.CustomButton();
        delp = new CustomGUI.CustomButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DateTable = new javax.swing.JTable();
        customButton4 = new CustomGUI.CustomButton();
        jLabel1 = new javax.swing.JLabel();
        customButton5 = new CustomGUI.CustomButton();
        recpro = new CustomGUI.CustomButton();
        jLabel2 = new javax.swing.JLabel();
        customButton6 = new CustomGUI.CustomButton();
        jLabel3 = new javax.swing.JLabel();
        customButton7 = new CustomGUI.CustomButton();
        jLabel4 = new javax.swing.JLabel();
        rad2 = new javax.swing.JRadioButton();
        pnumber = new CustomGUI.CustomTextBox();
        jLabel9 = new javax.swing.JLabel();
        Dep = new CustomGUI.CustomComboBox();
        customButton10 = new CustomGUI.CustomButton();
        rad4 = new javax.swing.JRadioButton();
        rad5 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        rad1.setBackground(new java.awt.Color(255, 255, 255));
        rad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad1.setSelected(true);
        rad1.setText("Number");

        rad3.setBackground(new java.awt.Color(255, 255, 255));
        rad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad3.setText("Location");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("search by :");

        addp.setText("Add");
        addp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addp.setMaximumSize(new java.awt.Dimension(83, 25));
        addp.setMinimumSize(new java.awt.Dimension(83, 25));
        addp.setPreferredSize(new java.awt.Dimension(83, 25));
        addp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpActionPerformed(evt);
            }
        });

        updatep.setText("Ubdate");
        updatep.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updatep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatepActionPerformed(evt);
            }
        });

        customButton9.setText("Search");
        customButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton9.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton9.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton9.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton9ActionPerformed(evt);
            }
        });

        delp.setText("Delete");
        delp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delpActionPerformed(evt);
            }
        });

        DateTable.setAutoCreateRowSorter(true);
        DateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Name", "Location", "Department Number", "Department Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DateTable.setAutoscrolls(false);
        DateTable.setGridColor(new java.awt.Color(102, 102, 102));
        DateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DateTable);

        customButton4.setText("Find");
        customButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Project Form");

        customButton5.setText("Get All");
        customButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });

        recpro.setText("Recover Last Deleted");
        recpro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recproActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Project Number :");

        customButton6.setText("Clear");
        customButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton6ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Project Name :");

        customButton7.setText("Back");
        customButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton7.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton7.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton7.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton7ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Location :");

        rad2.setBackground(new java.awt.Color(255, 255, 255));
        rad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad2.setText("Name");

        pnumber.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Department :");

        customButton10.setText("+");
        customButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton10.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton10.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton10.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton10ActionPerformed(evt);
            }
        });

        rad4.setBackground(new java.awt.Color(255, 255, 255));
        rad4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad4.setText("Deparment number");

        rad5.setBackground(new java.awt.Color(255, 255, 255));
        rad5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad5.setText("Deparment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(recpro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21)
                                            .addComponent(updatep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(delp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Dep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                    .addComponent(plocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rad1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rad2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rad4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rad5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(157, 157, 157)
                                        .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(480, 480, 480))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(plocation, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(customButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updatep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recpro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rad3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rad2)
                                .addComponent(rad1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad4)
                            .addComponent(rad5))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Project p = new Project();
    Project rec = new Project();
    Department d = new Department();

    private void setvalues(Project p) {
        p.setProjectName(pname.getText());
        p.setProjectNumber(Integer.parseInt(pnumber.getText()));
        p.setLocation(plocation.getText());
        String depname = Dep.getSelectedItem().toString();
        p.setDepartmentNumber(Integer.parseInt(d.getValue(depname)));
    }

    private void cleardata() {
        Tools.clearTextFields(this);
        pnumber.setText(p.getAutoNumber());
        addp.setEnabled(true);
        updatep.setEnabled(false);
        delp.setEnabled(false);
        pname.requestFocus();
    }

    private void addpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpActionPerformed
        setvalues(p);
        p.add();
        p.getAllRows(DateTable);
        cleardata();
    }//GEN-LAST:event_addpActionPerformed

    private void updatepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatepActionPerformed
        setvalues(p);
        p.update();
        p.getAllRows(DateTable);
        cleardata();
    }//GEN-LAST:event_updatepActionPerformed

    private void customButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton9ActionPerformed
        String search = "select * from ProjectData where ";
        if (rad1.isSelected()) {
            search += "ProjectNumber ";
        } else if (rad2.isSelected()) {
            search += "Project ";
        } else if (rad3.isSelected()) {
            search += "Location ";
        } else if (rad4.isSelected()) {
            search += "DepartmentNumber ";
        } else {
            search += "Department ";
        }
        search += " like '%" + Searchbar.getText() + "%'";
        d.filter(search, DateTable);
    }//GEN-LAST:event_customButton9ActionPerformed

    private void delpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delpActionPerformed
        if (Tools.showConfirmationDialog("Are you sure you want to delete this Department " + pnumber.getText())) {
            setvalues(p);
            setvalues(rec);
            p.delete();
            p.getAllRows(DateTable);
            cleardata();
            recpro.setEnabled(true);
        }
    }//GEN-LAST:event_delpActionPerformed

    private void DateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTableMouseClicked
        try {
            int row = DateTable.getSelectedRow();
            String pnum = DateTable.getValueAt(row, 0).toString();
            String pnam = DateTable.getValueAt(row, 1).toString();
            String ploc = DateTable.getValueAt(row, 2).toString();
            String depna = DateTable.getValueAt(row, 4).toString();
            pnumber.setText(pnum);
            pname.setText(pnam);
            plocation.setText(ploc);
            Dep.setSelectedItem(depna);

            addp.setEnabled(false);
            updatep.setEnabled(true);
            delp.setEnabled(true);
        } catch (Exception ex) {
            Tools.showMessageDialog(ex.getMessage());
        }
    }//GEN-LAST:event_DateTableMouseClicked

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        String dnum = (String) Tools.showInputDialog("Enter Project Number");
        if (dnum != null) {
            p.setProjectNumber(Integer.parseInt(dnum));
            p.getOneRow(DateTable);
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
        p.getAllRows(DateTable);
    }//GEN-LAST:event_customButton5ActionPerformed

    private void recproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recproActionPerformed
        if (Tools.showConfirmationDialog("do you want to recover Project (" + rec.getProjectName() + " , " + rec.getProjectNumber() + " )")) {

            int row = DateTable.getRowCount();
            for (int i = 0; i < row; i++) {
                int val = Integer.parseInt(DateTable.getValueAt(i, 0).toString());
                if (rec.getProjectNumber() == val) {
                    rec.setProjectNumber(Integer.parseInt(rec.getAutoNumber()));
                }
            }
            rec.add();
            p.getAllRows(DateTable);
            recpro.setEnabled(false);
        }
    }//GEN-LAST:event_recproActionPerformed

    private void customButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton6ActionPerformed
        cleardata();
    }//GEN-LAST:event_customButton6ActionPerformed

    private void customButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton7ActionPerformed
        this.dispose();
        Tools.openForm(new main());
    }//GEN-LAST:event_customButton7ActionPerformed

    private void customButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton10ActionPerformed
        int num = Integer.parseInt(d.getAutoNumber());
        String nam = (String) Tools.showInputDialog("Enter Department Name");
        if (nam != null) {
            String loc = (String) Tools.showInputDialog("Enter Department Location");
            if (loc != null) {
                d.setDepartmentName(nam);
                d.setDepartmentNumber(num);
                d.setLocation(loc);
                d.add();
            } else {
                Tools.showMessageDialog("the adding is canceled");
            }
        } else {
            Tools.showMessageDialog("the adding is canceled");
        }
        MysqlDatabaseManager.fillComboBox("DepartmentData", "Department", Dep);
    }//GEN-LAST:event_customButton10ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        searchgroup.add(rad1);
        searchgroup.add(rad2);
        searchgroup.add(rad3);
        searchgroup.add(rad4);
        searchgroup.add(rad5);
        cleardata();
        p.getAllRows(DateTable);
        DateTable.setBorder(null);
        DateTable.getTableHeader().setReorderingAllowed(false);
        recpro.setEnabled(false);
        MysqlDatabaseManager.fillComboBox("DepartmentData", "Department", Dep);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DateTable;
    private CustomGUI.CustomComboBox Dep;
    private CustomGUI.CustomTextBox Searchbar;
    private CustomGUI.CustomButton addp;
    private CustomGUI.CustomButton customButton10;
    private CustomGUI.CustomButton customButton4;
    private CustomGUI.CustomButton customButton5;
    private CustomGUI.CustomButton customButton6;
    private CustomGUI.CustomButton customButton7;
    private CustomGUI.CustomButton customButton9;
    private CustomGUI.CustomButton delp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private CustomGUI.CustomTextBox plocation;
    private CustomGUI.CustomTextBox pname;
    private CustomGUI.CustomTextBox pnumber;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JRadioButton rad5;
    private CustomGUI.CustomButton recpro;
    private javax.swing.ButtonGroup searchgroup;
    private CustomGUI.CustomButton updatep;
    // End of variables declaration//GEN-END:variables
}
