/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Database.MysqlDatabaseManager;
import Entity.Employee;
import Entity.Project;
import Entity.WorkOn;
import Utilities.Tools;

/**
 *
 * @author Ahmed
 */
public class Work_on_form extends javax.swing.JFrame {

    /**
     * Creates new form Work_on_form
     */
    public Work_on_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchgroup = new javax.swing.ButtonGroup();
        pro = new CustomGUI.CustomComboBox();
        customButton10 = new CustomGUI.CustomButton();
        jLabel9 = new javax.swing.JLabel();
        emp = new CustomGUI.CustomComboBox();
        customButton11 = new CustomGUI.CustomButton();
        jLabel10 = new javax.swing.JLabel();
        addb = new CustomGUI.CustomButton();
        delb = new CustomGUI.CustomButton();
        customButton4 = new CustomGUI.CustomButton();
        customButton5 = new CustomGUI.CustomButton();
        customButton7 = new CustomGUI.CustomButton();
        customButton9 = new CustomGUI.CustomButton();
        Searchbar = new CustomGUI.CustomTextBox();
        rad1 = new javax.swing.JRadioButton();
        rad4 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rad2 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DateTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        recwork = new CustomGUI.CustomButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        customButton10.setText("+");
        customButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton10.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton10.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton10.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton10ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Project :");

        customButton11.setText("+");
        customButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton11.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton11.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton11.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton11ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Employee :");

        addb.setText("Add");
        addb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addb.setMaximumSize(new java.awt.Dimension(83, 25));
        addb.setMinimumSize(new java.awt.Dimension(83, 25));
        addb.setPreferredSize(new java.awt.Dimension(83, 25));
        addb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbActionPerformed(evt);
            }
        });

        delb.setText("Delete");
        delb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbActionPerformed(evt);
            }
        });

        customButton4.setText("Find");
        customButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton4ActionPerformed(evt);
            }
        });

        customButton5.setText("Get All");
        customButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton5ActionPerformed(evt);
            }
        });

        customButton7.setText("Back");
        customButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton7.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton7.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton7.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton7ActionPerformed(evt);
            }
        });
        customButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customButton7KeyPressed(evt);
            }
        });

        customButton9.setText("Search");
        customButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customButton9.setMaximumSize(new java.awt.Dimension(83, 25));
        customButton9.setMinimumSize(new java.awt.Dimension(83, 25));
        customButton9.setPreferredSize(new java.awt.Dimension(83, 25));
        customButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton9ActionPerformed(evt);
            }
        });

        rad1.setBackground(new java.awt.Color(255, 255, 255));
        rad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad1.setSelected(true);
        rad1.setText("Employee number");

        rad4.setBackground(new java.awt.Color(255, 255, 255));
        rad4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad4.setText("Project name");
        rad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Search by :");

        rad2.setBackground(new java.awt.Color(255, 255, 255));
        rad2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad2.setText("Employee name");

        rad3.setBackground(new java.awt.Color(255, 255, 255));
        rad3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rad3.setText("Project number");
        rad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3ActionPerformed(evt);
            }
        });

        DateTable.setAutoCreateRowSorter(true);
        DateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "Employee Name", "Project Number", "Project Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DateTable.setAutoscrolls(false);
        DateTable.setGridColor(new java.awt.Color(102, 102, 102));
        DateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(DateTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Work on Form");

        recwork.setText("Recover Last Deleted");
        recwork.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(2, 2, 2))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emp, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                    .addComponent(pro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(recwork, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rad1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rad3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rad4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 140, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(497, 497, 497)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(emp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recwork, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rad1)
                                    .addComponent(jLabel11))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rad2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rad3)
                                    .addComponent(rad4))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(customButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    WorkOn wo = new WorkOn();
    WorkOn recwo = new WorkOn();
    Employee e = new Employee();
    Project p = new Project();

    private void setvalues(WorkOn wo) {
        String empname = emp.getSelectedItem().toString();
        String proname = pro.getSelectedItem().toString();
        int empno = Integer.parseInt(e.getValue(empname));
        int prono = Integer.parseInt(p.getValue(proname));
        wo.setEmployeeNumber(empno);
        wo.setProjectNumber(prono);
    }

    private void customButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton10ActionPerformed
        int num = Integer.parseInt(p.getAutoNumber());
        String nam = (String) Tools.showInputDialog("Enter Project Name");
        if (nam != null) {
            String loc = (String) Tools.showInputDialog("Enter project Location");
            if (loc != null) {
                String depn = (String) Tools.showInputDialog("Enter Department number");
                if (depn != null) {
                    p.setProjectName(nam);
                    p.setProjectNumber(num);
                    p.setLocation(loc);
                    p.setDepartmentNumber(Integer.parseInt(depn));
                    p.add();
                } else {
                    Tools.showMessageDialog("the adding is canceled");
                }
            } else {
                Tools.showMessageDialog("the adding is canceled");
            }
        } else {
            Tools.showMessageDialog("the adding is canceled");
        }
        MysqlDatabaseManager.fillComboBox("ProjectData", "Project", pro);
    }//GEN-LAST:event_customButton10ActionPerformed

    private void customButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton11ActionPerformed
        this.dispose();
        Tools.openForm(new Employee_form());
    }//GEN-LAST:event_customButton11ActionPerformed

    private void addbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbActionPerformed
        setvalues(wo);
        wo.add();
        wo.getAllRows(DateTable);
    }//GEN-LAST:event_addbActionPerformed

    private void delbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbActionPerformed
        if (Tools.showConfirmationDialog("Are you sure you want to delete this Relation")) {
            setvalues(wo);
            setvalues(recwo);
            wo.delete();
            wo.getAllRows(DateTable);
        }
        delb.setEnabled(false);
        addb.setEnabled(true);
        recwork.setEnabled(true);
    }//GEN-LAST:event_delbActionPerformed

    private void customButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton4ActionPerformed
        String dnum = (String) Tools.showInputDialog("Enter Employee Number");
        if (dnum != null) {
            wo.setEmployeeNumber(Integer.parseInt(dnum));
            String Query = "select * from WorkOnData where EmployeeNumber = " + Integer.parseInt(dnum);
            wo.filter(Query, DateTable);
        }
    }//GEN-LAST:event_customButton4ActionPerformed

    private void customButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton5ActionPerformed
        wo.getAllRows(DateTable);
    }//GEN-LAST:event_customButton5ActionPerformed

    private void customButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton7ActionPerformed
        this.dispose();
        Tools.openForm(new main());
    }//GEN-LAST:event_customButton7ActionPerformed

    private void customButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton9ActionPerformed
        String search = "select * from WorkOnData where ";
        if (rad1.isSelected()) {
            search += "EmployeeNumber ";
        } else if (rad2.isSelected()) {
            search += "EmployeeName ";
        } else if (rad3.isSelected()) {
            search += "ProjectNumber ";
        } else {
            search += "ProjectName ";
        }
        search += " like '%" + Searchbar.getText() + "%'";
        e.filter(search, DateTable);
    }//GEN-LAST:event_customButton9ActionPerformed

    private void rad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad4ActionPerformed

    private void rad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad3ActionPerformed

    private void DateTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTableMouseClicked
        try {
            int row = DateTable.getSelectedRow();
            String empnam = DateTable.getValueAt(row, 1).toString();
            String pronam = DateTable.getValueAt(row, 3).toString();

            pro.setSelectedItem(pronam);
            emp.setSelectedItem(empnam);

            addb.setEnabled(false);
            delb.setEnabled(true);
        } catch (Exception ex) {
            Tools.showMessageDialog(ex.getMessage());
        }
    }//GEN-LAST:event_DateTableMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        searchgroup.add(rad1);
        searchgroup.add(rad2);
        searchgroup.add(rad3);
        searchgroup.add(rad4);
        MysqlDatabaseManager.fillComboBox("Employee", "EmployeeName", emp);
        MysqlDatabaseManager.fillComboBox("Project", "ProjectName", pro);
        wo.getAllRows(DateTable);
        DateTable.getTableHeader().setReorderingAllowed(false);
        delb.setEnabled(false);
        recwork.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void recworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recworkActionPerformed
        if (Tools.showConfirmationDialog("do you want to recover the deleted relation")) {
            recwo.add();
            wo.getAllRows(DateTable);
            recwork.setEnabled(false);
        }
    }//GEN-LAST:event_recworkActionPerformed

    private void customButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customButton7KeyPressed

    }//GEN-LAST:event_customButton7KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Work_on_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Work_on_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Work_on_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Work_on_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Work_on_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DateTable;
    private CustomGUI.CustomTextBox Searchbar;
    private CustomGUI.CustomButton addb;
    private CustomGUI.CustomButton customButton10;
    private CustomGUI.CustomButton customButton11;
    private CustomGUI.CustomButton customButton4;
    private CustomGUI.CustomButton customButton5;
    private CustomGUI.CustomButton customButton7;
    private CustomGUI.CustomButton customButton9;
    private CustomGUI.CustomButton delb;
    private CustomGUI.CustomComboBox emp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private CustomGUI.CustomComboBox pro;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private CustomGUI.CustomButton recwork;
    private javax.swing.ButtonGroup searchgroup;
    // End of variables declaration//GEN-END:variables
}
